### PR TITLE
refactor js so it works

### PR DESCRIPTION
**Pull request by rsmoke**

### CODE REVIEW

**Review by britaumich — CHANGES_REQUESTED** [review]
On a small screen, the filters menu is not working. Nothing happens if I click on the Filter button.
Flash messages don't work correctly too. Try to update Announcements, for example. A message stays on the screen.
The feedback script works.

**Comment by rsmoke** [comment]
They are three js files. feedback, mobile-menu, flash
Please confirm they are working on a standard(lg+) screen.

These fingers may have never been in the small(al) screen

**Comment by rsmoke** [comment]
Now that I look at this, I see there two fish-message partials. I'll get rid of the duplicated one as soon as I am able

**Comment by britaumich** [comment]
It looks like the alert (like 'you are not authorized ...) and sign in/sign out flash messages work correctly, but the notification "... successfully updated" stays on the screen forever (until the page is reloaded)

**Comment by britaumich** [comment]
The mobile menu should work only on a mobile/small screen. It should show/hide the filter's sidebar. Right?

**Comment by rsmoke** [comment]
I fixed teh pathing to the js files. Please test again

**Comment by britaumich** [comment]
Sorry, I don't see any difference. I pulled the code and restarted the server. 
The "... successfully updated" message is not disappearing even if I click on the x. 
And I can't get filters on a small screen.
Does it work for you?
Tested in Chrome and Firefox

**Comment by rsmoke** [comment]
It is working on my system

-

Rick Smoke, Application Architect

For assistance please submit a request at:
https://lsa.umich.edu/technology-services/help-support.html

College of Literature, Science, and the Arts | University of Michigan
LSA Technology Services | 301 East Liberty Street, Ann Arbor, MI 48109

**Comment by britaumich** [comment]
I restarted the computer, but it still is not working correctly.
But everything works fine in the staging branch.
I don't know what else I can do.

**Comment by britaumich** [comment]
I can approve the request since it works on your computer and we'll test it on staging.
Do you want that?

**Comment by rsmoke** [comment]
I would like to know why it is not working for you. We can take care of it
on Monday

-

Rick Smoke, Application Architect

For assistance please submit a request at:
https://lsa.umich.edu/technology-services/help-support.html

College of Literature, Science, and the Arts | University of Michigan
LSA Technology Services | 301 East Liberty Street, Ann Arbor, MI 48109

**Pull request merged**
