### PR TITLE
Lra 193 mi classrooms fix autosubmit controller so that duration can be passed as a variable

### PR DESCRIPTION
**Pull request by britaumich**
Search fields in both Buildings and Classrooms pages work this way:

- the input string is handled by autosubmit_controller.js (search method), which calls index method (in Buildings or Classrooms controllers) and render the result (render turbo_stream: turbo_stream.replace)
- timeout is set up in the autosubmit_controller's search method
- @buildings or @classrooms are displayed in their own frames - I moved these frames to _listing partials
- pagination is moved to partials/_room_results_pagination.html.haml

tailwindcss-stimulus-components Autosave controller did not work for my search purpose. When I tried I got an error "Rails is not defined ...". And the Autosave description says that this component is designed to save drafts of records and the server side should check the params[:commit]. I am not sure if Autosave would work for our search.

I left only the search method in the autosubmit_controller.js because it works. success or error did not work for me. I think that we should research how ajax calls (or any other stimulus calls) and turbo work together to figure out how to check the results of these calls.

I also removed comments from buildings and classrooms index views

### CODE REVIEW

**Comment by dschmura** [comment]
In my testing I found that, on the Rooms Index and the Buildings index if you do a query in the text field, works great. However, if you refresh the page (or load the page directly from a copied url (http://localhost:3000/rooms?query=Undergraduate&min_capacity=1&max_capacity=600&school_or_college_name=) with the query, it returns a json blob. I suspect this has something to do with the turbo_stream. Is this something you can reproduce?

**Comment by britaumich** [comment]
Yes, I can reproduce that. I believe it's coming from the turbo_stream in buildings and rooms controllers: 
```
unless params[:query].nil?
      render turbo_stream: turbo_stream.replace(
        :roomListing,
        partial: "rooms/listing"
      )
 end
```
It works the same way in the VOD project with filters and reports. I tried to find a way to hide the query in the URL to avoid the problem when you reload the page but did not have any luck with that. 
Do you see any solution to this problem?

**Comment by dschmura** [comment]
I am not sure, but I am confident that there is a way. Given that confidence, I think you should leave it in and let’s figure it out ;-)

**Review by dschmura — APPROVED** [review]
Nice work Rita!

**Pull request merged**
