### PR TITLE
Add array of buildings that should not exist in database at this time

### PR DESCRIPTION
**Pull request by rsmoke**
added an array for populating programmatically. The array would be populated the bldrecnbr of 1000890 to remove the Perry building. 
This code will need to be removed if Perry ever joins the system

There is also a requirement of running these commands on the server in the console in this order:
* Room.find_by(building_bldrecnbr: 1000890).room_contact.delete
* Room.find_by(building_bldrecnbr: 1000890).room_characteristics.delete_all
* Room.find_by(building_bldrecnbr: 1000890).delete
* Building.find_by(bldrecnbr: 1000890).delete

### CODE REVIEW

**Review by britaumich — COMMENTED** [review]
I can't say that I like this solution.
You edited two classes adding the same remove_bldg = [1000890] array three times.
If we need to show the building again or hide more buildings we'll need to edit all of them.

I would rather put the remove_bldg array into the task file api_update_database.rake, where the buildings_codes array is (buildings added to the campus_codes array).

Also, my idea was to delete building(s) from the remove_bldg array after the script updates the database. In this case, we don't touch API classes and to remove buildings from the database we would edit only the remove_bldg array.

**Comment by rsmoke** [comment]
I don't like the idea of repeating myself too but the current structure of the updater task(s) is full of repetition and really doesn't support the SOLID principles. Without rewriting the task(s) to address the issues, I inserted the repetion. I am very interested in working on a rewrite of the whole update mechanism.

My idea was to prevent creating the building in the database so we would not need to delete the building and subsequently the Room(s) and the Room_Characteristics and the Contacts within the 4+ tables that are affected. With respect to the discussion at our meeting, we discussed removing this one building and if there is another request and we don't have better solution for the updater task(s) we can make a more elaborate fix.

**Comment by britaumich** [comment]
The code is full of repetitions because of the nature of APIs we are using. But I don't think we should add anything hardcoded into classes. The task file has arrays of campuses and additional buildings. I think we should add the array of buildings to delete into the same place. If you want to delete the building in classes' methods, pass the array as an argument. But I still think that the script (api_update_database) should delete the building after all tasks are finished. If they want to hide/show again a building, all we would do - edit the remove_bldg array.

**Comment by britaumich** [comment]
By the way, the pull request is not correct. The Perry building will be created in the database each time the script runs (in line 107 biuldings_api.rb) because it has 'classrooms'.

**Comment by rsmoke** [comment]
Ananta and I updated the code to remove the building as you describe and the rest will not populate since the building has been removed initially.

I created a CONST that sits at the top of the class and "remove the root" so the tree will never grow

**Review by anantaUM — APPROVED** [review]

**Comment by rsmoke** [comment]
Rita loves this solution

**Pull request merged**
