### PR TITLE
add link to mobile page

### PR DESCRIPTION
**Pull request by rsmoke**
I add the link using the Announcement.edit policy and am asking if there is a better way to control access/presentation of this link.

I reformatted the header slightly to accomodate the addition link item "AdminDoc"

### CODE REVIEW

**Comment by britaumich** [comment]
I can't say, that I like to have this link (without any pages) in the header.
How about adding the link to the footer?
Or to the Announcements page?

**Comment by rsmoke** [comment]
Can you tell me more why you don't like it in the header? I want it to be highly available and I set the AdminDoc to open in a new page to prevent interfering with the navigation.

**Comment by rsmoke** [comment]
I wonder if a second "Admin" header would work here. It could be just under the normal navigation

**Comment by britaumich** [comment]
I don't have a strong objection against the AdminDoc link in the header. I just don't like that a link (without a page) takes space in the header. No reasons - only feelings. You have to ask other people, Ananta, Maria and Jessica. I am not a style expert.

**Comment by rsmoke** [comment]
I am thinking that maybe make an actiontext admin notes page. 🤔

-

Rick Smoke, Application Architect

For assistance please submit a request at:
https://lsa.umich.edu/technology-services/help-support.html

College of Literature, Science, and the Arts | University of Michigan
LSA Technology Services | 301 East Liberty Street, Ann Arbor, MI 48109

**Comment by britaumich** [comment]
I am not sure what you mean. What is the "admin notes page"?

**Review by britaumich — APPROVED** [review]
I approve the request. The code is good.
You can merge it to the staging server, so we can talk about it at the meeting.

**Comment by rsmoke** [comment]
I was a bit at a loss as to the best spot.

-

Rick Smoke, Application Architect

For assistance please submit a request at:
https://lsa.umich.edu/technology-services/help-support.html

College of Literature, Science, and the Arts | University of Michigan
LSA Technology Services | 301 East Liberty Street, Ann Arbor, MI 48109

**Pull request merged**
