### PR TITLE
Lra 267 mclassrooms update room index page

### PR DESCRIPTION
**Pull request by britaumich**
I created a new branch for this ticket to make the code cleaner. Something in the old branch messed up styles in multiple places.
I kept images; created a link from the whole card and added buildings nick_names to cards.

### CODE REVIEW

**Review by rsmoke — DISMISSED** [review]
I believe this is a great improvement!

**Comment by rsmoke** [comment]
Is this ready to removed from 'DRAFT' status? If so, click the [Ready for review] button above

**Comment by britaumich** [comment]
@rsmoke But how about making images the same size? You said that that should be part of this ticket.

**Comment by rsmoke** [comment]
In agree, there images being the Dave size is important

**Comment by britaumich** [comment]
Sorry, I am not sure that I understand your comment. What is 'the Dave size'? What is important? Dave's images all have different sizes.

**Comment by rsmoke** [comment]
that was supposed say same size not dave size

**Comment by britaumich** [comment]
Now buildings images are the same size as the placeholder "M". Seems to work for images that I have.

**Review by rsmoke — APPROVED** [review]
This looks to be the code that we needed!

**Pull request merged**
