### PR TITLE
LRA-311 Display room record number for admins

### PR DESCRIPTION
**Pull request by anantaUM**
As per discussion with Maria, it should have following display style:

- underneath facility ID, italiic/nonbold, body size

### CODE REVIEW

**Review by britaumich — APPROVED** [review]
Usually we check [if current_user.admin ...] in views and controllers.
We check session["user_admin"] if a user's attribute '.admin' is not available.
I don't know if it makes any difference. 
If I remember correctly, the 'admin' attribute was created to use in policies, because session variables are not available in policies. Then I guess it doesn't matter what to check, if both - a session variable and a user's attribute - are available.
I approve the request, but you can wait for Rick's opinion.

**Comment by anantaUM** [comment]
> Usually we check [if current_user.admin ...] in views and controllers. We check session["user_admin"] if a user's attribute '.admin' is not available. I don't know if it makes any difference. If I remember correctly, the 'admin' attribute was created to use in policies, because session variables are not available in policies. Then I guess it doesn't matter what to check, if both - a session variable and a user's attribute - are available. I approve the request, but you can wait for Rick's opinion.

In this file, we have _session["user_admin"]_  being used on line 25 and line 167 as well.

**Review by rsmoke — APPROVED** [review]
thanks sir, please have Q/A eyeballs look at this for layout concerns

**Comment by britaumich** [comment]
Yes, it is. Too complicated to explain here, why session["user_admin"] is in these lines. If you want I'll tell you. But it confirms the statement that there is no difference in what to use to check the user's role.

**Pull request merged**
