### PR TITLE
LRA-338-fix-room-edit-view

### PR DESCRIPTION
**Pull request by rsmoke**
I added a few more layout elements to help the display of the images and there categories

### CODE REVIEW

**Review by britaumich — COMMENTED** [review]
Could you please do the following on the edit room page with several images uploaded?
1. Click remove one image. Say yes.
2. Click remove another image. Say yes.
3. Do you see a thumbnail of the first image on the page?

**Comment by rsmoke** [comment]
I updated the redirect and this is working on local

**Comment by britaumich** [comment]
sorry, I still have the problem that I mentioned in my first comment

**Review by britaumich — CHANGES_REQUESTED** [review]
The js controller works only when you want to remove an image. 
You removed a confirmation question from the Remove button - why?
Actually, the confirmation should be moved to the js controller because we don't want a message to be displayed if we cancel removing an image.
I tried that and canceling worked perfectly. But then I had the same problem (as the original one) when I tried to remove an image.

I think a correct solution is a separate form for every image. In this case, we can add another image instead of a removed one without saving the whole form (and going to the show page and back to edit).

**Comment by rsmoke** [comment]
I went with the confirmation cancel as a design decision. I considered the separate the form and would rather do a full Stimulus Turbo frame/stream solution but we need to fix the stimulus install first.

**Review by britaumich — APPROVED** [review]
You forced me to do that

**Pull request merged**
