### PR TITLE
LRA-302-mclassrooms-admin-update-admin-ui-for-image-uploads

### PR DESCRIPTION
**Pull request by rsmoke**
Added a toggle to replace the checkbox for visibilty

Redesigned the room image management page

### CODE REVIEW

**Review by britaumich — COMMENTED** [review]
At the meeting, we talked about adding a zoom control to the images gallery. I thought you showed us that it can be done, but I can't find how. 

Оn the room's edit page the Save button is still not visible enough, especially compared to the [Update a Building Image or Floor Maps] button.

Also, I believe we talked about adding some kind of descriptors and notes to the edit page to explain where a room image is displayed; an image vs gallery, etc.

**Comment by rsmoke** [comment]
1. There is not a zoom control available in the stimulus-lightbox component
2. I added a √ for image file type and image size
3. I added a description section to the edit page form Room image management etc.
4. Relabelled subit button and added a second one at the top of the form

**Comment by britaumich** [comment]
I pushed two updates:

- I replaced the “Back” label on the building show page with "Back to the Building Index Page”.
- On the room edit page moved the [Update a Building Image or Floor Maps] button to the bottom of the page, after Show|Back links

**Comment by britaumich** [comment]
I like two "Save Room" buttons

**Comment by britaumich** [comment]
I thinks the instruction in the room edit page should have images' restrictions:
acceptable types - png, jpeg, pdf
file size cannot exceed 5Mbyte"

**Review by britaumich — APPROVED** [review]
Looks good.

**Pull request merged**
