### PR TITLE
LRA-335  MClassrooms search filter bug - cursor jump while typing search terms

### PR DESCRIPTION
**Pull request by anantaUM**

### CODE REVIEW

**Review by rsmoke — COMMENTED** [review]
I am seeing this 'Eager Loading' detection issue in my console:
_It is coming from the bullet gem_
```
user: rsmoke
08:32:48 web.1     | GET /rooms?direction=&school_or_college_name=&building_name=East+ha&classroom_name=&min_capacity=1&max_capacity=600
08:32:48 web.1     | USE eager loading detected
08:32:48 web.1     |   Room => [:room_image_attachment]
08:32:48 web.1     |   Add to your query: .includes([:room_image_attachment])
08:32:48 web.1     | Call stack
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/helpers/application_helper.rb:37:in `room_thumbnail_image'
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/views/rooms/_room_row.html.erb:7:in `block in _app_views_rooms__room_row_html_erb__104769559337968884_48040'
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/views/rooms/_room_row.html.erb:1:in `_app_views_rooms__room_row_html_erb__104769559337968884_48040'
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/views/rooms/_listing.html.erb:28:in `block (2 levels) in _app_views_rooms__listing_html_erb__451444308142399310_45000'
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/views/rooms/_listing.html.erb:27:in `block in _app_views_rooms__listing_html_erb__451444308142399310_45000'
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/views/rooms/_listing.html.erb:1:in `_app_views_rooms__listing_html_erb__451444308142399310_45000'
08:32:48 web.1     |   /Users/rsmoke/RailsApps/mi_classrooms/app/controllers/rooms_controller.rb:52:in `index'
```

I need to look into the proper fix and what the overall cost really is.

**Comment by anantaUM** [comment]
Yes, this message was coming in staging even before I made changes as part of this pull request. I asked Rita about it yesterday.

**Review by rsmoke — APPROVED** [review]
This is a nice UI fix.

**Comment by rsmoke** [comment]
I will wait on merging until Rita reviews this PR (per our conversations last week)

**Comment by britaumich** [comment]
@anantaUM I tested the filter and it worked.
Now I can't load the application anymore (stylesheets and js are not compiling or loading or who knows what?)

Have you tested the following: run a search, go to a room from the search and go back to the index page. Do you still have that search result?
That 'back' button was why we did not use turbo in the rooms controller in the index method. 
You did that a little bit differently than I did, so I hope it works now, but I can't test it because I can't load the application.
Please test it.

**Comment by britaumich** [comment]
@anantaUM 
I restarted my computer and the application works now.
The browser's Back button works fine too. But The button "Back to previous page" on the show page doesn't work: it returns to the All Buildings list, not to the search list.
Please check.

**Comment by rsmoke** [comment]
I believe the not jumping in filters trumps the [back to previous page] and that should be deleted in lieu for the non bouncy filter advantage

**Comment by anantaUM** [comment]
Removed 'Back to Previous Page' link from room show page and room filters glossary page.

**Review by rsmoke — APPROVED** [review]
Looks great. The fixed bounce in the filters is a very good improvement

**Pull request merged**
