### PR TITLE
Lra 282 mclassroom make sure all buildings have a nick name when imported

### PR DESCRIPTION
**Pull request by britaumich**
Replace a nick_name with a name where it doesn't matter what is displayed.
Check if a nick_name is present before displaying it.

### CODE REVIEW

**Review by rsmoke — COMMENTED** [review]
Wouldn't it be better to keep nick_name and when importing the data from the Data Warehouse setting a default value. This could be done by setting a default value in the database by writing a value in when the imported data is missing.

**Comment by britaumich** [comment]
There is no default value for the nick_name. What do you want to use as a default value for the nick_name? All nick_names are entered manually with update commands that are in the seed.erb file.
On the Room index page, buildings cards have names and nick_names displayed. If we put something else then correct nick_names into a nick_name field displaying nick_names would not make sense.

**Comment by rsmoke** [comment]
I would put in logic that if there is not a value then do not display the
nick_name.

-

Rick Smoke, Application Architect

For assistance please submit a request at:
https://lsa.umich.edu/technology-services/help-support.html

College of Literature, Science, and the Arts | University of Michigan
LSA Technology Services | 301 East Liberty Street, Ann Arbor, MI 48109

**Comment by britaumich** [comment]
And this is exactly what I did in buildings/_building_detail.html.erb and rooms/_building_card.html.erb:
<% if @building.nick_name.present? %>
   (<%= @building.nick_name %>)
<% end %>

In other files, I replaced a nick_name with a name because a field that is used there should always have value, or we don't use these files at all (but it is still better to use a non-empty field).

**Review by rsmoke — APPROVED** [review]
This is the best thing since sliced bread!!!!

**Pull request merged**
