### PR TITLE
FEATURE: Panoramas to room show view

### PR DESCRIPTION
**Pull request by dschmura**
This commit adds the ability to load and display panoramas on the room show view. Panoramas are loaded loaded using Active Storage and rendered using the pannellum javascript library. (** If a panorama is not found in active storage for aparticular room it falls back to using the room_image helper, which in turn falls back to a placeholder image if no image is found.)

The show page renders the new _room_panorama.html.haml partial, which in turn utilized a pannellum stimulus controller.

The pannellum.js library has a css file that is currently loaded in the application.js entrypoint (import 'pannellum/build/pannellum.css'), whcih I don't love (I would prefer we only load the css if we need it), but trying to load it within the pannellum controller was causing issues on my development machine, so there it is for now.

Pannellum requires imagemagick be installed on the machine. For my dev machine (Macintosh with M1 chip) I installed imagemagick using homebrew (brew install imagemagick), which you will need to do as well on your development machines. Hatchbox provided a script to install it on our server instances, which I have already done.

I also created a rooms.sass as a place to put the styles related to rooms. I haven't refactored any of the other sass files to move the rooms specific styling that is scattered about, but now there is a place for them.

Future functionality requests will likely include the ability to copy a 'still' of the image (similar to the pannellum preview) so that Moni can send it in an email, or fax or whatever.

I loaded a pano for the first room on the staging server https://mi-classrooms-staging.lsa.umich.edu/rooms/2026586 which I am also attaching to this pull request so you can load it on your dev machines as well. (Go to edit and add a Room panorama).

### CODE REVIEW

**Comment by britaumich** [comment]
@dschmura Dave, I loaded the branch to test (imagemagick is installed). I want to verify that it works as you intend it to work. I loaded a panorama (that you attached above) by going to Room Edit view -> Room panorama. Now that panorama is shown instead of the room image with the [click to load panorama] button in the middle of the image. If I click on the button panorama is displayed nicely
Screen Shot 2021-12-14 at 8 15 44 AM

I have some questions:

- If a room's panorama exists are we going to display a panorama instead of a room image? On the staging server, we have a link [show 360] in the [Room Show view] to click to display a panorama. 
- If there is no panorama and no room image, a placeholder takes too much space:
Screen Shot 2021-12-14 at 8 22 13 AM
-

**Comment by dschmura** [comment]
Thanks @britaumich. You are correct, that is the expected behavior. When we designed the feature in MiLocations it was intended to lessen (and eventually remove) the need for the room_image. This will remove a huge amount of work for Dave Crandall who has to collect the image separately from the panoramas he is already taking.

That being said, I didn't do a lot on the design end of this feature. It might make sense to show a different missing image image. The Block M doesn't really communicate that there isn't an image or panorama available for that room.

**Comment by britaumich** [comment]
@dschmura Thanks, good. 
But if a room panorama and an image are missing a placeholder image (block M or any other) should not take so much space, I think. Right now on the server, the M-placeholder is a small image

Screen Shot 2021-12-14 at 12 04 34 PM

Could you edit styles in the room's show view to make the M-block smaller?

**Comment by dschmura** [comment]
Is there a design spec to reference?

**Comment by britaumich** [comment]
Sorry, I am not sure that I understand your question.
This is a URL: https://mi-classrooms-staging.lsa.umich.edu/rooms/2017595
It's the rooms/show.html.erb

**Review by rsmoke — CHANGES_REQUESTED** [review]
You need to manage the placeholder image size so it is properly proportioned. Ask Maria for a design spec if you need help with this.

**Comment by dschmura** [comment]
@britaumich @rsmoke @anantaUM 
I have added a 'image missing' image. It still has the map icon (I couldn't find the original. I think it'll do, at least for getting the feature in.

**Review by rsmoke — APPROVED** [review]
This looks great. I like how the images are panorama or fail to room image then placholder if the first two are missing

**Pull request merged**
